fix(avo-1866): check which user wants to fetch others
viaacode/avo2-client pull request #1333
Opened 2022-05-09 08:22 UTC by ian-emsens-shd

https://meemoo.atlassian.net/browse/AVO-1866

2022-05-11 07:24 UTC, bertyhell approved these changes

2022-05-11 07:26 UTC, bertyhell requested changes
see global remark

2022-05-11 07:43 UTC, bertyhell commented
When i login as:
accounts+educatieveauteur@meemoo.be
password in 1password under `meemoo test accounts avo2`

and i go to the workspace and then to the links i see (4) in the tab, but i don't see any items in the table:
![image](https://user-images.githubusercontent.com/1710840/167795586-fea0502b-87e4-4cb1-80e0-13bba6fdd840.png)

When i checkout the master branch i do see the items in the table:
![image](https://user-images.githubusercontent.com/1710840/167795713-ddd55a87-d545-4e6c-a0b6-742b51ef3c03.png)

2022-05-12 08:55 UTC, ian-emsens-shd commented on src/admin/shared/components/ContentPicker/item-providers/profile.ts
> +};
🚨

2022-05-12 11:19 UTC, bertyhell approved these changes

2022-05-16 07:38 UTC, merged