feat(avo-1934): response overview
viaacode/avo2-client pull request #1360
Opened 2022-06-21 10:49 UTC by bartnaessens

extracted translations

2022-06-22 11:52 UTC, ian-emsens-shd requested changes
De `AssignmentResponses`-view heeft in het algemeen een kleine poetsbeurt nodig.

2022-06-22 11:52 UTC, ian-emsens-shd commented on src/assignment/views/AssignmentResponses.tsx
> +				);
Zijn dit de juiste permissions voor deze pagina? Het lijkt me veiliger om dit onder een aparte permission te hangen.

2022-06-22 11:52 UTC, ian-emsens-shd commented on src/assignment/views/AssignmentResponses.tsx
> +				);
Copy-paste leftovers; zelfde vertaling & functie-naam

2022-06-24 08:28 UTC, bartnaessens commented on src/assignment/views/AssignmentResponses.tsx
> +				);
fixed

2022-06-24 09:25 UTC, ian-emsens-shd approved these changes

2022-06-24 09:25 UTC, merged