feat(avo-1945): add modal to trim fragment when adding to existing assignment
viaacode/avo2-client pull request #1370
Opened 2022-06-28 14:14 UTC by bartnaessens

refactor add to collection modal to also add to assignments
Intergrate modal in the item detail

2022-06-29 07:11 UTC, ian-emsens-shd requested changes

2022-06-29 11:05 UTC, ian-emsens-shd approved these changes

2022-06-30 13:30 UTC, bertyhell approved these changes

2022-07-01 07:38 UTC, bartnaessens commented on src/shared/translations/nl.json
> +  "item/components/modals/add-to-assignment-modal___overslaan": "",
fixed

2022-07-01 07:38 UTC, merged