feat(avo-1910): add pupil assignment response page header
viaacode/avo2-client pull request #1375
Opened 2022-06-29 15:54 UTC by bertyhell

part of https://meemoo.atlassian.net/browse/AVO-1910

Requires a Proxy PR: https://github.com/viaacode/avo2-proxy/pull/451

example url: http://localhost:8080/opdrachten/cd0c043f-9db2-4cc2-a668-dab0b7ab72ef

![image](https://user-images.githubusercontent.com/1710840/176481475-14ea10c7-785d-4db9-abb2-1dc85a1943fa.png)

2022-06-30 11:58 UTC, bartnaessens approved these changes

2022-06-30 11:58 UTC, bartnaessens commented on src/assignment/hooks/assignment-pupil-tabs.tsx
> +import { IconNameSchema } from '@viaa/avo2-components/src/components/Icon/Icon.types';
both imports from /dist and /src

2022-06-30 14:21 UTC, bertyhell commented on src/assignment/hooks/assignment-pupil-tabs.tsx
> +import { IconNameSchema } from '@viaa/avo2-components/src/components/Icon/Icon.types';
fixed

2022-07-01 11:25 UTC, ian-emsens-shd requested changes

2022-07-01 11:25 UTC, ian-emsens-shd commented on src/assignment/hooks/assignment-pupil-tabs.tsx
> +				['ZOEK', 'BOUW'].includes(assignment?.assignment_type)
Use the corresponding enum instead of strings

2022-07-01 11:25 UTC, ian-emsens-shd commented on src/assignment/views/AssignmentResponseEdit.tsx
> +import './AssignmentEdit.scss';
```suggestion
import './AssignmentResponseEdit.scss';
```

2022-07-01 12:24 UTC, ian-emsens-shd approved these changes

2022-07-01 12:24 UTC, merged