Feature/avo 1833
viaacode/avo2-client pull request #1544
Opened 2022-09-05 13:47 UTC by ian-emsens-shd

2022-09-07 09:03 UTC, bertyhell approved these changes

2022-09-07 09:09 UTC, bertyhell requested changes

2022-09-07 09:09 UTC, bertyhell commented on src/settings/components/LinkedAccounts.tsx
> +									{/* Previously disabled for pupils due to https://meemoo.atlassian.net/browse/AVO-2062 */}
do we still need this?

2022-09-07 09:09 UTC, bertyhell commented on src/settings/components/LinkedAccounts.tsx
> +									<div>{renderIdpLinkControls('VLAAMSEOVERHEID')}</div>
button is not the same size on mobile:
![image](https://user-images.githubusercontent.com/1710840/188839160-a0dff26a-778d-458a-8879-d4869cfed4dc.png)

2022-09-07 14:19 UTC, ian-emsens-shd commented on src/settings/components/LinkedAccounts.tsx
> +									{/* Previously disabled for pupils due to https://meemoo.atlassian.net/browse/AVO-2062 */}
I'd prefer to keep the record here

2022-09-08 08:06 UTC, bertyhell commented
The link screen is quite confusing now.
![image](https://user-images.githubusercontent.com/1710840/189069430-ad2f1bb1-1e15-4352-8bb1-f5a92f30cac3.png)


Would we change it to this design instead?
![image](https://user-images.githubusercontent.com/1710840/189069439-633974f2-e7d2-45a4-9119-ee8304ed1696.png)

2022-09-08 11:16 UTC, merged