Feature/avo 2638 lom fields input
viaacode/avo2-client pull request #1760
Opened 2023-06-06 13:38 UTC by SHDBramVandenbussche

[AVO-2638](https://meemoo.atlassian.net/browse/AVO-2638)
[AVO-2682](https://meemoo.atlassian.net/browse/AVO-2682)

[Avo2-Proxy PR](url)

<img width="407" alt="image" src="https://github.com/viaacode/avo2-client/assets/113341869/1a3d76bc-11ef-4289-9d1f-1a0e0e1e7872">

2023-06-07 10:33 UTC, bertyhell requested changes

2023-06-07 10:33 UTC, bertyhell commented on src/collection/components/CollectionOrBundleEdit.tsx
> +					omit(collectionState.currentCollection, ['loms', 'contributors']),
it might be andy to have a single helper for this
stripCollectionFieldsBeforeInsertOrUpdate(collection)

2023-06-07 10:33 UTC, bertyhell commented on src/collection/components/CollectionOrBundleEdit.tsx
> +										'Er is iets misgegaan met het updaten van de publicatie details van de collectie'
```suggestion
										'Het updaten van de publicatie details van de collectie is mislukt'
```

2023-06-07 10:33 UTC, bertyhell commented on src/collection/components/CollectionOrBundleEdit.tsx
> +										'Er is iets misgegaan met het updaten van de publicatie details van de bundel'
```suggestion
										'Het updaten van de publicatie details van de bundel is mislukt'
```

2023-06-07 10:33 UTC, bertyhell commented on src/collection/components/CollectionOrBundleEditMetaData.tsx
> +		if (!isEmpty(collection) && collection.loms) {
you should only use isEmpty for checking arrays or empty objects, not for null/undefined checks. You can use isNil for that.

2023-06-07 10:33 UTC, bertyhell commented on src/collection/components/CollectionOrBundleEditMetaData.tsx
> +			});
saving these fields in a local state usually causes strange issues where this state doesn't stay in sync with the parent lom fields state

Its better to just make this a computed value:
```typescript
const lomFields = useMemo(() => {
	const groupedLoms = groupLoms(collection.loms);
	return {
		educationLevels: mapLomsToLomFields(
			groupedLoms[LomSchemeTypeEnum.structure] as Avo.Lom.LomEntry[]
		) || [],
		subjects: mapLomsToLomFields(
			groupedLoms[LomSchemeTypeEnum.subject] as Avo.Lom.LomEntry[]
		) || [],
		themes: mapLomsToLomFields(
			groupedLoms[LomSchemeTypeEnum.theme] as Avo.Lom.LomEntry[]
		) || [],
	}
}, [collection.loms]);
```

![IMG_20230607_121424 (1)](https://github.com/viaacode/avo2-client/assets/1710840/53245197-6e82-47c8-9d00-b901eac8ca0d)

2023-06-07 10:33 UTC, bertyhell commented on src/collection/components/CollectionOrBundleEditMetaData.tsx
>  		changeCollectionState({
don't keep local state, but update the parent collection state directly

2023-06-07 10:33 UTC, bertyhell commented on src/shared/components/LomFieldsInput/LomFieldsInput.tsx
> +	const [themesOptions, setThemesOptions] = useState<Avo.Lom.LomField[]>([]);
don't use state to store stuff that needs to react to changes in parent state
just use a getEducationLevelOptions() function that does this dyanmically on each render
if it is too slow we can wrap it in a useMemo hook

2023-06-07 10:33 UTC, bertyhell commented on src/shared/components/LomFieldsInput/LomFieldsInput.tsx
> +	}, [setThemesOptions]);
wouldn't it be easier to wrap these service functions in a react-query useQuery wrapper and then you get the isLoading and isError booleans for free?

2023-06-07 10:33 UTC, bertyhell commented on src/shared/components/LomFieldsInput/LomFieldsInput.tsx
> +		}
why do you need to do this?
can't you just replace the whole array:
```
// compute the new contexts:
const handleEducationLevelsChange = (newLevels: Avo.Lom.LomField[]) => {
	const newContexts = getContextsFromEducationLevels(newLevels);
	onChange({ contexts: newContexts, educationLevels: newLevels });
}
```

2023-06-07 10:33 UTC, bertyhell commented on src/shared/services/lom.service.ts
> +						parents: subjectIds,
the parents of the subjects would be the education levels, so this variable name is confusing
```suggestion
						parents: educationLevelIds,
```

2023-06-07 10:33 UTC, bertyhell commented on src/shared/services/lom.service.ts
> +						parents: themesIds,
```suggestion
						parents: [...subjectIds, ...educationLevelIds],
```

2023-06-12 11:08 UTC, WardVerc1 approved these changes

2023-06-12 13:42 UTC, bertyhell approved these changes

2023-06-12 13:42 UTC, bertyhell commented on src/assignment/assignment.helper.tsx
> +	const themes: Avo.Lom.LomField[] = groupedLoms['themes'] || [];
```suggestion
	const educationLevels: Avo.Lom.LomField[] = groupedLoms.educationLevels || [];
	const subjects: Avo.Lom.LomField[] = groupedLoms.subjects || [];
	const themes: Avo.Lom.LomField[] = groupedLoms.themes || [];
```

2023-06-12 13:42 UTC, bertyhell commented on src/shared/components/LomFieldsInput/LomFieldsInput.tsx
> +		if (scheme === 'educationLevels') {
```suggestion
		if (scheme === LomSchemeType.educationLevel) {
```

2023-06-12 13:42 UTC, bertyhell commented on src/shared/components/LomFieldsInput/LomFieldsInput.tsx
> +			flatLomList = concat(flatLomList, parentContexts);
no need to use a lodash function here:
```suggestion
			flatLomList = [...flatLomList, ...parentContexts];
```

2023-06-12 14:37 UTC, SHDBramVandenbussche commented on src/shared/types/lom.ts
>  }
I will fix this in the last PR of based on this PR

2023-06-12 14:37 UTC, SHDBramVandenbussche commented on src/shared/types/lom.ts
>  }
I will fix this in the last PR of based on this PR

2023-06-13 06:36 UTC, merged