fix(avo-2597): fix width role dropdown button in share with colleagues component
viaacode/avo2-client pull request #1805
Opened 2023-07-03 12:07 UTC by SHDBramVandenbussche

[AVO-2597](https://meemoo.atlassian.net/browse/AVO-2597)

Before: 
![image](https://github.com/viaacode/avo2-client/assets/113341869/2b66a2a5-47bb-4b8c-9201-d486df71e8e5)

After:
![image](https://github.com/viaacode/avo2-client/assets/113341869/789b9f79-387e-41de-a178-9f72c8eb35c8)

2023-07-03 12:39 UTC, WardVerc1 approved these changes

2023-07-04 15:02 UTC, bertyhell requested changes

2023-07-04 15:02 UTC, bertyhell commented on src/shared/components/ShareWithColleagues/ShareWithColleagues.scss
> +		&.c-button--primary {
we should also fix the hover issue:
![image](https://github.com/viaacode/avo2-client/assets/1710840/7d3d47f4-597a-445b-a22e-62796c8f7638)

![image](https://github.com/viaacode/avo2-client/assets/1710840/440cb0bc-692b-473e-98e5-8df1b27238b8)

The correct way of doing this is to use Button type="secondary" or maybe tertiary
and not override the styling of the primary button style

2023-07-06 12:53 UTC, bertyhell approved these changes

2023-07-06 13:04 UTC, merged